services:
  invoice-web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    restart: unless-stopped
    networks:
      - invoice-net
    ports:
      - 80
    depends_on:
      invoice-php-fpm:
        condition: service_healthy

  invoice-php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - invoice-net
    healthcheck:
      test: SCRIPT_FILENAME=/ping.php REQUEST_METHOD=GET cgi-fcgi -bind -connect localhost:9000 | grep 'pong' || exit 1
      interval: 60s
      retries: 3
      start_period: 10s
      timeout: 5s
    depends_on:
      invoice-mysql:
        condition: service_healthy

  invoice-mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: eJVzC2siywYlD64QQ2vcM
      MYSQL_DATABASE: lara_db_faturas_jjemplacamentos
    ports:
      - 3306
    volumes:
      - invoice_db_data:/var/lib/mysql
    networks:
      - invoice-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  invoice-redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - invoice-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  invoice-net:

volumes:
  invoice_db_data:
