version: '3'
services:
    php-invoice-ninja:
        restart: on-failure
        build:
            context: ../../
            dockerfile: docker/prod/php/Dockerfile
        volumes:
            - storage:/var/www/storage
        ports:
            - 9000
        depends_on:
            - db-invoice-ninja

    db-invoice-ninja:
        image: mariadb:latest
        restart: on-failure
        environment:
            MARIADB_ROOT_PASSWORD: $DB_PASSWORD
            MARIADB_DATABASE: $DB_NAME
        ports:
            - 3306

volumes:
    storage:
